sudo: required
services:
  - docker

before_install:
  - docker build -t georgigeorgiev9323/docker-react -f Dockerfile.dev .

script:
  - docker run georgigeorgiev9323/docker-react npm run test -- --coverage